import { getOsEnv } from "./env.config";

export const secretConfig = {
  jwtSecretKey: getOsEnv("JWT_SECRET_KEY"),
  accessSecretKey: getOsEnv("ACCESS_SECRET_KEY"),
  refreshSecretKey: getOsEnv("REFRESH_SECRET_KEY"),
  jwtExpirationTime: getOsEnv("JWT_EXPIRATION_TIME"),
  aesEncryptionKey: getOsEnv("AES_ENCRYPTION_KEY"),
  refreshTokenExpiry: getOsEnv("REFRESH_TOKEN_EXPIRY"),
  accessTokenExpiry: getOsEnv("ACCESS_TOKEN_EXPIRY"),
  cloudinaryCloudName: getOsEnv("CLOUDINARY_CLOUD_NAME"),
  cloudinaryApiKey: getOsEnv("CLOUDINARY_API_KEY"),
  cloudinaryApiSecret: getOsEnv("CLOUDINARY_API_SECRET"),
  geminiApiKey: getOsEnv("GEMINI_API_KEY"),
  mailtrapApiKey: getOsEnv("MAILTRAP_API_KEY"),
  senderEmail: getOsEnv("SENDER_EMAIL"),
  backendUrl: getOsEnv("BACKEND_URL"),
  senderName: getOsEnv("SENDER_NAME"),
  emailVerificationSecretKey: getOsEnv("EMAIL_VERIFICATION_SECRET_KEY"),
  emailTokenExpiry: getOsEnv("EMAIL_TOKEN_EXPIRY"),
  mailtrapSandboxUsername: getOsEnv("MAILTRAP_SANDBOX_USERNAME"),
  mailtrapSandboxPassword: getOsEnv("MAILTRAP_SANDBOX_PASSWORD"),
  mailtrapHost: getOsEnv("MAILTRAP_HOST"),
  mailtrapPort: getOsEnv("MAILTRAP_PORT"),
};
